services:
  # # Backend
  # backend:
  #   build:
  #     context: .
  #     dockerfile: ./backend/Dockerfile
  #   ports:
  #     - "3000:3000"
  #   environment:
  #     - FRONTEND_URL=${FRONTEND_URL}
  #     - DATABASE_URL=${DATABASE_URL}
  #     - DIRECT_URL=${DIRECT_URL}
  #   env_file:
  #     - .env

  # # Frontend
  # frontend:
  #   build:
  #     context: .
  #     dockerfile: ./frontend/Dockerfile
  #   environment:
  #     - VITE_BACKEND_URL=${VITE_BACKEND_URL}
  #   depends_on:
  #     - backend
  #   ports:
  #     - "5173:80"
  #   env_file:
  #     - .env

  # Database
  database:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    command: -c fsync=off -c full_page_writes=off -c synchronous_commit=off -c max_connections=500
    ports:
      - 10001:5432
